import { OBLIGATIONS } from './deadlines.js';

/**
 * Localized Art. 50(1) disclosure strings — all 24 official EU languages.
 * Machine-quality translations: have a native speaker review before launch
 * in markets where precision matters.
 */
export const DISCLOSURE_STRINGS: Record<string, string> = {
  bg: 'Вие взаимодействате със система с изкуствен интелект. Отговорите се генерират автоматично.',
  cs: 'Komunikujete se systémem umělé inteligence. Odpovědi jsou generovány automaticky.',
  da: 'Du interagerer med et AI-system. Svar genereres automatisk.',
  de: 'Sie interagieren mit einem KI-System. Antworten werden automatisch generiert.',
  el: 'Αλληλεπιδράτε με ένα σύστημα τεχνητής νοημοσύνης. Οι απαντήσεις δημιουργούνται αυτόματα.',
  en: 'You are interacting with an AI system. Responses are generated automatically.',
  es: 'Está interactuando con un sistema de IA. Las respuestas se generan automáticamente.',
  et: 'Te suhtlete tehisintellekti süsteemiga. Vastused genereeritakse automaatselt.',
  fi: 'Olet vuorovaikutuksessa tekoälyjärjestelmän kanssa. Vastaukset luodaan automaattisesti.',
  fr: "Vous interagissez avec un système d'IA. Les réponses sont générées automatiquement.",
  ga: 'Tá tú ag idirghníomhú le córas intleachta saorga. Gintear freagraí go huathoibríoch.',
  hr: 'Komunicirate sa sustavom umjetne inteligencije. Odgovori se generiraju automatski.',
  hu: 'Ön egy mesterséges intelligencia rendszerrel kommunikál. A válaszok automatikusan készülnek.',
  it: 'Stai interagendo con un sistema di IA. Le risposte sono generate automaticamente.',
  lt: 'Jūs bendraujate su dirbtinio intelekto sistema. Atsakymai generuojami automatiškai.',
  lv: 'Jūs sazināties ar mākslīgā intelekta sistēmu. Atbildes tiek ģenerētas automātiski.',
  mt: "Qed tinteraġixxi ma' sistema ta' intelliġenza artifiċjali. It-tweġibiet jiġu ġġenerati awtomatikament.",
  nl: 'U communiceert met een AI-systeem. Antwoorden worden automatisch gegenereerd.',
  pl: 'Rozmawiasz z systemem AI. Odpowiedzi są generowane automatycznie.',
  pt: 'Está a interagir com um sistema de IA. As respostas são geradas automaticamente.',
  ro: 'Interacționați cu un sistem de inteligență artificială. Răspunsurile sunt generate automat.',
  sk: 'Komunikujete so systémom umelej inteligencie. Odpovede sa generujú automaticky.',
  sl: 'Komunicirate s sistemom umetne inteligence. Odgovori se ustvarjajo samodejno.',
  sv: 'Du interagerar med ett AI-system. Svaren genereras automatiskt.',
};

export function disclosureHtml(lang = 'en'): string {
  const text = DISCLOSURE_STRINGS[lang] ?? DISCLOSURE_STRINGS.en;
  return `<!-- EU AI Act Art. 50(1) disclosure — generated by article50 -->
<div data-ai-disclosure="interaction" role="note" lang="${lang}"
     style="font: 13px/1.4 system-ui, sans-serif; padding: 8px 12px; border-radius: 8px;
            background: #eef2ff; color: #3730a3; display: flex; gap: 8px; align-items: center;">
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
    <path d="M12 2a7 7 0 0 1 7 7v1h1a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-1.1A7 7 0 0 1 5.1 18H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h1V9a7 7 0 0 1 7-7Z" stroke="currentColor" stroke-width="1.6"/>
    <circle cx="9" cy="12" r="1.2" fill="currentColor"/><circle cx="15" cy="12" r="1.2" fill="currentColor"/>
  </svg>
  <span>${text}</span>
</div>`;
}

export function disclosureReact(lang = 'en'): string {
  const text = DISCLOSURE_STRINGS[lang] ?? DISCLOSURE_STRINGS.en;
  return `// EU AI Act Art. 50(1) disclosure — generated by article50
export function AiDisclosure({ text = ${JSON.stringify(text)} }: { text?: string }) {
  return (
    <div
      data-ai-disclosure="interaction"
      role="note"
      lang="${lang}"
      style={{
        font: '13px/1.4 system-ui, sans-serif',
        padding: '8px 12px',
        borderRadius: 8,
        background: '#eef2ff',
        color: '#3730a3',
      }}
    >
      {text}
    </div>
  );
}`;
}

export interface MarkingOptions {
  /** AI system/model used to generate the content, e.g. "gpt-4o". */
  model?: string;
  provider?: string;
}

/** Machine-readable Art. 50(2) marking for HTML documents. */
export function markingHtml(options: MarkingOptions = {}): string {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'CreativeWork',
    isAiGenerated: true,
    'iptc:digitalSourceType': 'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia',
    ...(options.model ? { 'a50:model': options.model } : {}),
    ...(options.provider ? { 'a50:provider': options.provider } : {}),
  };
  return `<!-- EU AI Act Art. 50(2) machine-readable marking — generated by article50 -->
<meta name="ai-generated" content="true">
<meta name="ai-disclosure" content="machine-readable; article50">
<script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2)}
</script>`;
}

/** Inject Art. 50(2) marking into an HTML document's <head>. */
export function markHtml(html: string, options: MarkingOptions = {}): string {
  const block = markingHtml(options);
  if (/<head[^>]*>/i.test(html)) {
    return html.replace(/<head([^>]*)>/i, (m) => `${m}\n${block}\n`);
  }
  return `${block}\n${html}`;
}

/** Recommended HTTP response header for AI-generated payloads (API responses, files). */
export const MARKING_HTTP_HEADER = 'X-AI-Generated: true; spec="eu-ai-act-art-50-2"';

export function policyMarkdown(productName = 'Our product', now: Date = new Date()): string {
  const date = now.toISOString().slice(0, 10);
  const rows = Object.values(OBLIGATIONS)
    .map((o) => `| ${o.article} | ${o.title} | ${o.deadline} | ☐ |`)
    .join('\n');
  return `# AI Transparency Policy — ${productName}

_Last updated: ${date}. Drafted with [article50](https://github.com/article50). This is a template, not legal advice._

## 1. Scope

This policy describes how ${productName} meets the transparency obligations of
Article 50 of the EU AI Act (Regulation (EU) 2024/1689, as amended by the Digital Omnibus).

## 2. AI interaction disclosure (Art. 50(1))

Where users interact directly with an AI system (chat, voice, or agent interfaces),
we display a clear notice at the start of the interaction, e.g.:

> ${DISCLOSURE_STRINGS.en}

## 3. Machine-readable marking of AI-generated content (Art. 50(2))

Content generated or materially modified by our AI systems is marked in a
machine-readable format using one or more of:

- \`<meta name="ai-generated" content="true">\` and JSON-LD declarations in HTML
- IPTC \`digitalSourceType: trainedAlgorithmicMedia\` metadata in media files
- \`${MARKING_HTTP_HEADER}\` on API responses

## 4. Deepfakes and public-interest text (Art. 50(4))

Where we publish AI-generated or manipulated image, audio, or video content
resembling real persons, places, or events, we disclose the artificial origin
visibly and in metadata.

## 5. Obligation register

| Article | Obligation | Applies from | Implemented |
| --- | --- | --- | --- |
${rows}

## 6. Review

This policy is reviewed on every release that adds or changes an AI feature,
verified in CI with \`a50 scan --ci\`.
`;
}
